# The following docker-compose file is used to deploy a postgres database container
# It contains one containers (Postgres) and one optional container (PG Admin).


services:

  # PostGres
  train_delay_postgres:
    image: postgres:14
    container_name: train_delay_postgres
    # For production, change user and password
    environment:
      - POSTGRES_USER=root     # Change this for your production environment
      - POSTGRES_PASSWORD=root # Change this for your production environment
      - POSTGRES_DB=train_delay_db    # Avoid changing this, unless you know what you are doing
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    # Comment ports if you don't want the database to be accessible from the host
    ports:
      - "5432:5432" # Comment this line for production to avoid exposing the database
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 60s
      timeout: 10s
      retries: 3
    # networks:
    #   - app_network



  # Optional: PG Admin
  # container_pgadmin:
  #   image: dpage/pgadmin4:latest
  #   container_name: pgadmin
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=mail@mail.com
  #     - PGADMIN_DEFAULT_PASSWORD=password
  #   ports:
  #     - "5050:80"
  #   restart: always
  #   networks:
  #     - app_network


# Networks
# networks:
#   app_network:
#     external: true